service: servo

provider:
  name: google
  labels:
    application: syllabi
  stage: dev
  runtime: nodejs12
  region: asia-south1
  project: oxford-hackathon
  credentials: ~/.gcloud/keyfile.json

frameworkVersion: '2'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  create:
    handler: create
    events:
      - http: path
  
  all:
    handler: all
    events:
      - http: path